SIMULATOR_STEPS = 300
NUM_INDIVS = 50
INPUT_SIZE = 8
NUM_HEAL_ZONES = 7
HEAL_ZONE_RADIUS = 30
NUM_RAD_ZONES = 6
RAD_ZONE_RADIUS = 25
RAD_ZONE_MOVE_DELAY = 3
GRID_SIZE = 300
MAX_LENGTH = GRID_SIZE * 1.414
WINDOW_SCALE = 3
PROFILER = False

MUTATION_RATE = 0.1
MUTATION_MAGNITUDE = 0.01
SELECTION_RATE = 0.3
LOAD_MODELS = True