SIMULATOR_STEPS = 300
NUM_INDIVS = 60
INPUT_SIZE = 8
NUM_HEAL_ZONES = 7
HEAL_ZONE_RADIUS = 30
NUM_RAD_ZONES = 6
RAD_ZONE_RADIUS = 25
RAD_ZONE_MOVE_DELAY = 3
GRID_SIZE = 300
MAX_LENGTH = GRID_SIZE * 1.414
WINDOW_SCALE = 3
PROFILER = False

MUTATION_RATE = 0.1
MUTATION_MAGNITUDE = 0.01
SELECTION_RATE = 1 / 3
LOAD_MODELS = True
GATE_DISABLE_RATE = 0.003

# NOTE: NUM_INDIVS must be evenly divisible by SELECTION_RATE, and the inverse of SELECTION_RATE must be an integer.