SIMULATOR_STEPS = 300
NUM_INDIVS = 120
INPUT_SIZE = 10
NUM_HEAL_ZONES = 1
HEAL_ZONE_RADIUS = 125
NUM_RAD_ZONES = 1
RAD_ZONE_RADIUS = 15
RAD_ZONE_MOVE_DELAY = 3
RAD_ZONE_ENABLE_MOVEMENT = False
GRID_SIZE = 300
MAX_LENGTH = GRID_SIZE * 1.414
WINDOW_SCALE = 3
PROFILER = False

MUTATION_RATE = 0.001
MUTATION_MAGNITUDE = 0.001
SELECTION_RATE = 1 / 3
LOAD_MODELS = True
GATE_DISABLE_RATE = 0.003

ENABLE_GATING = False

# NOTE: NUM_INDIVS must be evenly divisible by SELECTION_RATE, and the inverse of SELECTION_RATE must be an integer.